M48
; DRILL file {KiCad 9.0.2} date 2026-02-18T14:35:04-0600
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-02-18T14:35:04-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
%
G90
G05
T1
X64.45Y-54.2
T2
X64.45Y-58.7
M30
